<?php

namespace FC\CatalogBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CatalogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CatalogRepository extends EntityRepository
{
}
